### PR TITLE
Created django project. ref #1

### PR DESCRIPTION
**Pull request by Prince-linux**
Pls accept my setup

### CODE REVIEW

**Comment by Prince-linux** [comment]
oh kk

**Comment by Prince-linux** [comment]
but with the .gitignore file,, what exactly do you want me to do with it ??

**Comment by lcabrini** [comment]
Edit .gitignore and add a line with db.sqlite3

**Comment by Prince-linux** [comment]
done please

**Comment by Prince-linux** [comment]
done please

**Comment by Prince-linux** [comment]
+1

**Pull request merged**
